server:
  port: ${PORT_SERVER_SYSTEM:8201}

spring:
  datasource:
    dynamic:
      primary: primary
      datasource:
        primary:
          driver-class-name: ${DATASOURCE_DRIVER:com.mysql.cj.jdbc.Driver}
          url: jdbc:${DATASOURCE_DB_TYPE:mysql}://${DATASOURCE_HOST:127.0.0.1}:${DATASOURCE_PORT:3306}/${NACOS_NAMESPACE:dev}_${DB_NAME_SYSTEM:system}?${DATASOURCE_PARAM:useUnicode=true&characterEncoding=utf8&connectTimeout=1000&socketTimeout=3000&autoReconnect=true&zeroDateTimeBehavior=convertToNull&rewriteBatchedStatements=true&serverTimezone=Asia/Shanghai}
          username: ${DATASOURCE_USERNAME:root}
          password: ${DATASOURCE_PASSWORD:root}

  flyway:
    table: system_flyway_history

mybatis-plus:
  type-aliases-package: com.zclcs.common.core.entity.system
  mapper-locations: classpath:com/zclcs/server/system/mapper/*.xml

my:
  cloud:
    security:
      enable: true
      anon-uris: /v2/api-docs,/v2/api-docs-ext

seata:
  config:
    nacos:
      data-id: server-system-seata.properties
