version: '3'

services:
  # 生产可以不用部署
  server-generator:
    image: ${CLOUD_DEPOSITORY_IP_PORT}${CLOUD_DEPOSITORY_URL}/server-generator:${CLOUD_DEPOSITORY_TAG}
    container_name: ${NACOS_NAMESPACE}_server-generator
    network_mode: host
    command: sh -c "/wait && java ${JAVA_OPS_PREFIX} ${SERVER_GENERATOR_JAVA_OPS} ${JAVA_OPS_SUFFIX} -cp /app/resources:/app/classes:/app/libs/* ${SERVER_GENERATOR_MAIN_CLASS}"
    environment:
      WAIT_HOSTS: ${NACOS_HOST}:${SEATA_PORT}, ${NACOS_HOST}:${PORT_SERVER_SYSTEM}
      WAIT_SLEEP_INTERVAL: ${DOCKER_WAIT_SLEEP_INTERVAL}
      WAIT_HOST_CONNECT_TIMEOUT: ${DOCKER_WAIT_HOST_CONNECT_TIMEOUT}
      WAIT_TIMEOUT: ${DOCKER_WAIT_TIMEOUT}
    volumes:
      - ./log/server-generator:/log/server-generator
      - ./log/server-generator/skywalking:/agent/logs
      - ${CLOUD_AGENT_CONFIG}
    healthcheck:
      test: [ "CMD-SHELL", "curl -sS ${NACOS_HOST}:${PORT_SERVER_GENERATOR} || exit 1" ]
      interval: ${DOCKER_HEALTHCHECK_INTERVAL}
      timeout: ${DOCKER_HEALTHCHECK_TIMEOUT}
      retries: ${DOCKER_HEALTHCHECK_RETRIES}
    env_file: .env